// Ponto de entrada do núcleo pedagógico (reaproveitável no React Native).
export * from './types'
export * from './rng'
export * from './themes'
export * from './numberWords'
export * from './answer'
export * from './feedback'
export * from './generator'
export * from './prompts'
export * from './validation'
export * from './tutor'
export { BNCC_SKILLS, findSkill } from './bncc/skills'
export { ALL_TEMPLATES, findTemplate, templatesForFocus } from './templates'
export { answerNumbers } from './templates/helpers'
